// vue/src/components/Todos/Add.vue
<template>
  <div class="card mt-2 mb-2">
    <div class="card-header">
      <h3 class="text-white">Add Todo</h3>
    </div>
    <div class="card-body">
      <form @submit.prevent="addNewTodo()">
        <div class="form-group">
          <label for="description">Description</label>
          <input type="text" class="form-control" placeholder="Description" v-model="description" />
        </div>
        <input type="submit" class="btn btn-add" value="Add Todo" />
      </form>
    </div>
  </div>
</template>

<script>
import axios from "axios";
export default {
  data() {
    return {
      description: ""
    };
  },
  methods: {
    async addNewTodo() {
      let { data } = await axios.post("http://localhost:5000/todos", {
        description: this.description
      });
      if (data.status) {
        this.description = "";
      }
      this.$emit("newTodoAdd", data);
    }
  }
};
</script>

<style scoped>
.card {
  border-radius: 0;
}
.card-header {
  border-radius: 0;
  background: rgba(0, 0, 0, 0.4);
}
.form-control {
  border-radius: 0;
}
.btn-add {
  color: #fff;
  border-radius: 0;
  background: rgba(30, 132, 73, 0.9);
}
</style>

// angular/src/app/components/Todos/add/add.component.ts
import { Component, OnInit, Output, EventEmitter } from "@angular/core";
import { TodoService } from "src/app/services/todo.service";

@Component({
  selector: "app-add",
  templateUrl: "./add.component.html",
  styleUrls: ["./add.component.css"]
})
export class AddComponent implements OnInit {
  newTodo: string = "";
  @Output() addedTodo: EventEmitter<any> = new EventEmitter();

  constructor(private todoService: TodoService) {}
  ngOnInit() {}

  addTodo = async () => {
    let data = await this.todoService.addNewTodo(this.newTodo);
    data.subscribe((res: any) => {
      console.log(res);
      if (res.status) {
        this.newTodo = "";
      }
      this.addedTodo.emit(res);
    });
  };
}

<div class="card mb-2">
  <div class="card-header">
    <h3>Add Todo</h3>
  </div>
  <div class="card-body">
    <form (submit)="addTodo()">
      <div class="form-group">
        <label for="description">Todo Description</label>
        <input
          type="text"
          name="description"
          [(ngModel)]="newTodo"
          placeholder="Todo Description"
          class="form-control"
        />
      </div>
      <input type="submit" class="btn btn-angular" value="Add Todo" />
    </form>
  </div>
</div>
