// vue/src/components/Todos/Todo.vue
<template>
  <li class="list-group-item mt-2 mb-2">
    <div class="row">
      <div class="col-9">
        <p :class="todo.status ? 'todo-text' : ''">{{ todo.description }}</p>
        <div
          :class="
          todo.status
            ? 'badge badge-pill badge-success'
            : 'badge  badge-pill badge-danger'
        "
        >{{ todo.status ? "Completed" : "Pending" }}</div>
      </div>
      <div class="col-3">
        <button class="btn btn-danger mr-2" @click="deleteTodo()">✕</button>
        <button class="btn btn-info" @click="completeTodo()" :disabled="todo.status">✓</button>
      </div>
    </div>
  </li>
</template>

<script>
import axios from "axios";
export default {
  props: { todo: Object },
  methods: {
    async deleteTodo() {
      let { data } = await axios.delete(
        "http://localhost:5000/todos?id=" + this.todo._id
      );
      this.$emit("onTodoDelete", {
        todo: this.todo,
        message: data.message,
        status: data.status
      });
    },
    async completeTodo() {
      let { data } = await axios.put(
        "http://localhost:5000/todos?id=" + this.todo._id,
        {}
      );
      this.$emit("onTodoUpdate", {
        todo: this.todo,
        message: data.message,
        status: data.status
      });
    }
  }
};
</script>

<style scoped>
.list-group-item {
  border-radius: 0;
}
.btn {
  border-radius: 0;
}
.todo-text {
  text-decoration: line-through;
}
</style>

// angular/src/app/components/Todos/todo/todo.component.ts
import { Component, OnInit, Input, Output, EventEmitter } from "@angular/core";
import { TodoService } from "src/app/services/todo.service";

@Component({
  selector: "app-todo",
  templateUrl: "./todo.component.html",
  styleUrls: ["./todo.component.css"]
})
export class TodoComponent implements OnInit {
  @Input() todo: any;
  @Output() todoDelete: EventEmitter<any> = new EventEmitter();
  @Output() todoEdit: EventEmitter<any> = new EventEmitter();
  constructor(private todoService: TodoService) {}
  ngOnInit() {}

  completeTodo = async () => {
    let data = await this.todoService.completeTodo(this.todo._id);
    data.subscribe((res: any) => {
      this.todo = res.updatedTodo;
      this.todoEdit.emit(res);
    });
  };

  deleteTodo = async () => {
    this.todoDelete.emit(this.todo._id);
  };
}

<li class="list-group-item mt-2 mb-2">
  <div class="row">
    <div class="col-9">
      <p [class]="todo.status ? 'todo-text' : ''">{{ todo.description }}</p>
      <div
        [class]="
          todo.status
            ? 'badge badge-pill badge-success'
            : 'badge  badge-pill badge-danger'
        "
      >
        {{ todo.status ? "Completed" : "Pending" }}
      </div>
    </div>
    <div class="col-3">
      <button class="btn btn-danger mr-2" (click)="deleteTodo()">✕</button>
      <button
        class="btn btn-info"
        (click)="completeTodo()"
        [disabled]="todo.status"
      >
        ✓
      </button>
    </div>
  </div>
</li>
