// angular/src/app/components/Todos/todos/todos.component.ts
import { Component, OnInit } from "@angular/core";
import { TodoService } from "src/app/services/todo.service";

@Component({
  selector: "app-todos",
  templateUrl: "./todos.component.html",
  styleUrls: ["./todos.component.css"]
})
export class TodosComponent implements OnInit {
  todos: any[] = [];
  success: Boolean = false;
  message: string = "";

  constructor(private todoService: TodoService) {}

  ngOnInit() {
    this.getTodos();
  }

  // Initial Message states
  initNotification = res => {
    this.success = res.status;
    this.message = res.message;
    setTimeout(() => {
      this.message = "";
      this.success = false;
    }, 3000);
  };

  /**
   * Fetch all the todos from the database
   */
  getTodos = async () => {
    let data = await this.todoService.getTodos();
    data.subscribe((res: any) => {
      if (res.status) {
        this.todos = res.todos;
      } else {
        // Error
        this.initNotification(res);
      }
    });
  };

  /**
   * Delete Todo
   */
  deleteTodo = async id => {
    let data = await this.todoService.todoDelete(id);
    data.subscribe((res: any) => {
      if (res.status) {
        this.todos = this.todos.filter(todo => todo._id != res.todo._id);
      }
      this.initNotification(res);
    });
  };

  /**
   * New Todo Add
   */
  newTodoAdd(res) {
    if (res.status) {
      this.todos = [res.todo, ...this.todos];
    }
    this.initNotification(res);
  }
}

<div
  *ngIf="message"
  [class]="success ? 'alert alert-success' : 'alert alert-danger'"
>
  {{ message }}
</div>
<app-add (addedTodo)="newTodoAdd($event)"></app-add>
<ul class="list-group" *ngIf="todos.length">
  <app-todo
    *ngFor="let todo of todos"
    [todo]="todo"
    (todoDelete)="deleteTodo($event)"
    (todoEdit)="initNotification($event)"
  ></app-todo>
</ul>
<div class="mt-5 mb-5" *ngIf="!todos.length">
  <p class="text-secondary text-center">No Todos...</p>
</div>

// vue/src/components/Todos/Todos.vue
<template>
  <div class="mt-3">
    <div v-if="message" :class="success ? 'alert alert-success': 'alert alert-danger'">{{ message }}</div>
    <Add @newTodoAdd="addTodo" />
    <ul class="list-group" v-if="todos.length">
      <Todo
        v-for="todo in todos"
        :key="todo._id"
        :todo="todo"
        @onTodoDelete="deleteTodo"
        @onTodoUpdate="updateTodo"
      />
    </ul>
    <div class="mt-5 mb-5" v-else>
      <p class="text-secondary text-center">No Todos...</p>
    </div>
  </div>
</template>

<script>
const BASEURL = "http://localhost:5000";
import axios from "axios";
import Todo from "./Todo";
import Add from "./Add";

export default {
  components: {
    Todo,
    Add
  },
  data() {
    return {
      todos: [],
      message: "",
      success: false
    };
  },
  methods: {
    async getTodos() {
      let { data } = await axios.get(`${BASEURL}/todos`);
      let res = data;
      if (res.status) {
        this.todos = res.todos;
      } else {
        this.initNotification(res);
      }
    },

    deleteTodo(res) {
      if (res.status) {
        this.todos = this.todos.filter(todo => todo._id != res.todo._id);
      }
      this.initNotification(res);
    },

    async updateTodo(res) {
      if (res.status) {
        this.getTodos();
      }
      this.initNotification(res);
    },

    addTodo(res) {
      this.todos = [res.todo, ...this.todos];
      this.initNotification(res);
    },

    initNotification(res) {
      this.message = res.message;
      this.success = res.status;
      setTimeout(() => {
        this.message = "";
        this.success = false;
      }, 3000);
    }
  },
  created() {
    this.getTodos();
  }
};
</script>

<style scoped>
.alert {
  border-radius: 0;
  color: #fff;
}
.alert-success {
  background: rgba(30, 132, 73);
}

.alert-danger {
  background: rgba(203, 67, 53);
}
</style>
